DROP TABLE IF EXISTS fersaSSTest.ObsoleteItems_vs_FinanceReport;

CREATE TABLE fersaSSTest.ObsoleteItems_vs_FinanceReport AS

WITH
PARAMS AS (
    SELECT DATE '2026-04-30' AS CLOSINGDATE
),

OBSOLETE AS (
    SELECT
        oia.SUBSIDIARYID,
        oia.INVENTLOCATIONID,
        oia.ITEMID,
        SUM(oia.OBSOLETEQTY) AS QTY,
        SUM(oia.OBSOLETEQTY * oia.UNITCOST_EUR) AS AMOUNT
    FROM FERSASS.ObsoleteItems_ALL oia
    CROSS JOIN PARAMS P
    WHERE
        oia.FLAG IN (
            'DAILY',
            'DAILY-FBEA-FG'
        )
        AND (
               (oia.INVENTLOCATIONID NOT LIKE 'T_%' AND oia.SUBSIDIARYID <> 'FBRA')
            OR (oia.SUBSIDIARYID = 'PAUS' AND oia.INVENTLOCATIONID NOT LIKE 'T_P0%')
            OR oia.SUBSIDIARYID = 'FBRA'
        )
    GROUP BY
        oia.SUBSIDIARYID,
        oia.INVENTLOCATIONID,
        oia.ITEMID
),

OBSOLETE_AGG AS (
    SELECT
        SUBSIDIARYID,
        ITEMID,
        SUM(QTY) AS QTY,
        ROUND(SUM(AMOUNT), 2) AS AMOUNT
    FROM OBSOLETE
    GROUP BY
        SUBSIDIARYID,
        ITEMID
),

FINANCEOBSOLETE AS (
    SELECT
        mfo.SUBSIDIARYID,
        mfo.ITEMID,
        SUM(mfo.STOCKQTY) AS QTY,
        SUM(mfo.CALCULATEDSDAMOUNT_EUR) AS AMOUNTSTOCK,
        SUM(mfo.FINANCIALSDAMOUNT_EUR) AS AMOUNTFINANCE
    FROM fersads.ds_monthlyfinancialobsoletes_edc mfo
    CROSS JOIN PARAMS P
    -- Ajusta este campo si en finance se llama distinto
    WHERE mfo.UPLOADMONTH = P.CLOSINGDATE
    GROUP BY
        mfo.SUBSIDIARYID,
        mfo.ITEMID
)

SELECT
    CASE
        WHEN o.SUBSIDIARYID IS NULL THEN 'SOLO_FINANCE'
        WHEN fo.SUBSIDIARYID IS NULL THEN 'SOLO_CALC'
        WHEN ABS(COALESCE(o.QTY, 0) - COALESCE(fo.QTY, 0)) > 0.01 THEN 'DIF_QTY'
        WHEN ABS(COALESCE(o.AMOUNT, 0) - COALESCE(fo.AMOUNTSTOCK, 0)) > 0.01 THEN 'DIF_AMOUNT_STOCK'
        WHEN ABS(COALESCE(o.AMOUNT, 0) - COALESCE(fo.AMOUNTFINANCE, 0)) > 0.01 THEN 'DIF_AMOUNT_FINANCE'
        ELSE 'OK'
    END AS DEBUG_STATUS,
    COALESCE(o.SUBSIDIARYID, fo.SUBSIDIARYID) AS SUBSIDIARYID,
    COALESCE(o.ITEMID, fo.ITEMID) AS ITEMID,
    o.QTY AS QTY_CALC,
    fo.QTY AS QTY_FINREP,
    ROUND(o.AMOUNT, 2) AS AMOUNT_CALC,
    ROUND(fo.AMOUNTSTOCK, 2) AS AMOUNTSTOCK_FINREP,
    ROUND(fo.AMOUNTFINANCE, 2) AS AMOUNTFINANCE_FINREP,
    COALESCE(o.QTY, 0) - COALESCE(fo.QTY, 0) AS DIFF_QTY,
    ROUND(COALESCE(o.AMOUNT, 0) - COALESCE(fo.AMOUNTSTOCK, 0), 2) AS DIFF_AMOUNT_STOCK,
    ROUND(COALESCE(o.AMOUNT, 0) - COALESCE(fo.AMOUNTFINANCE, 0), 2) AS DIFF_AMOUNT_FINANCE
FROM OBSOLETE_AGG o
FULL OUTER JOIN FINANCEOBSOLETE fo
    ON o.SUBSIDIARYID = fo.SUBSIDIARYID
   AND o.ITEMID = fo.ITEMID
WHERE
       o.SUBSIDIARYID IS NULL
    OR fo.SUBSIDIARYID IS NULL
    OR ABS(COALESCE(o.QTY, 0) - COALESCE(fo.QTY, 0)) > 0.01
    OR ABS(COALESCE(o.AMOUNT, 0) - COALESCE(fo.AMOUNTSTOCK, 0)) > 0.01
    OR ABS(COALESCE(o.AMOUNT, 0) - COALESCE(fo.AMOUNTFINANCE, 0)) > 0.01
ORDER BY
    DEBUG_STATUS,
    SUBSIDIARYID,
    ABS(COALESCE(o.AMOUNT, 0) - COALESCE(fo.AMOUNTSTOCK, 0)) DESC;