WITH 
SUBSIDIARY AS
(
	SELECT DISTINCT HASH(UPPER(DATAAREAID)) FROM fersads.ds_InventTrans_FER UNION ALL SELECT DISTINCT HASH(UPPER(DATAAREAID)) FROM fersads.ds_InventTrans_CHN_HIST
),

PARAMS AS (
    SELECT
    		DATE '2026-04-30' AS CLOSINGDATE,
    		'FINANCIAL_CLOSING' AS STOCK_SOURCE, -- valores posibles: 'FINANCIAL_CLOSING' o 'INVENTSUM'
    		'PHYSICAL' AS DATE_MODE -- valores: 'PHYSICAL' o 'FINANCIAL'
),

ExchangeRatesLatest AS (
    SELECT
        erda.FROMCURRENCYCODE,
        erda.TOCURRENCYCODE,
        erda.EXCHANGERATE,
        ROW_NUMBER() OVER (
            PARTITION BY erda.FROMCURRENCYCODE, erda.TOCURRENCYCODE
            ORDER BY erda.VALIDFROM DESC
        ) AS RN
    FROM fersadv.ExchangeRateDaily_ALL erda
    CROSS JOIN PARAMS P
    WHERE erda.VALIDFROM <= P.CLOSINGDATE
),
ExchangeRatesPairs AS (
    -- Directos
    SELECT
        FROMCURRENCYCODE,
        TOCURRENCYCODE,
        EXCHANGERATE
    FROM ExchangeRatesLatest
    WHERE RN = 1

    UNION ALL

    -- Inversos
    SELECT
        TOCURRENCYCODE AS FROMCURRENCYCODE,
        FROMCURRENCYCODE AS TOCURRENCYCODE,
        1 / NULLIF(EXCHANGERATE, 0) AS EXCHANGERATE
    FROM ExchangeRatesLatest
    WHERE RN = 1
),
ExchangeRates AS (
    SELECT
        C.CURRENCY,
        COALESCE(
            MAX(CASE WHEN D_EUR.TOCURRENCYCODE = 'EUR' THEN D_EUR.EXCHANGERATE END),
            MAX(D_USD.EXCHANGERATE * USD_EUR.EXCHANGERATE)
        ) AS EXCHANGERATE_EUR,
        COALESCE(
            MAX(CASE WHEN D_USD.TOCURRENCYCODE = 'USD' THEN D_USD.EXCHANGERATE END),
            MAX(D_EUR.EXCHANGERATE * EUR_USD.EXCHANGERATE)
        ) AS EXCHANGERATE_USD
    FROM (
        SELECT DISTINCT CURRENCY
        FROM fersaSS.ds_StockFinancialMonthClosing
    ) C
    LEFT JOIN ExchangeRatesPairs D_EUR
        ON D_EUR.FROMCURRENCYCODE = C.CURRENCY
        AND D_EUR.TOCURRENCYCODE = 'EUR'
    LEFT JOIN ExchangeRatesPairs D_USD
        ON D_USD.FROMCURRENCYCODE = C.CURRENCY
        AND D_USD.TOCURRENCYCODE = 'USD'
    LEFT JOIN ExchangeRatesPairs EUR_USD
        ON EUR_USD.FROMCURRENCYCODE = 'EUR'
        AND EUR_USD.TOCURRENCYCODE = 'USD'
    LEFT JOIN ExchangeRatesPairs USD_EUR
        ON USD_EUR.FROMCURRENCYCODE = 'USD'
        AND USD_EUR.TOCURRENCYCODE = 'EUR'
    GROUP BY
        C.CURRENCY
)

SELECT DISTINCT
    S.CURRENCY
FROM fersaSS.ds_StockFinancialMonthClosing S
LEFT JOIN ExchangeRates ER
    ON ER.CURRENCY = S.CURRENCY
CROSS JOIN PARAMS P
WHERE S.CLOSINGDATE = P.CLOSINGDATE
  AND S.QUANTITY > 0
  AND (
      ER.EXCHANGERATE_EUR IS NULL
      OR ER.EXCHANGERATE_USD IS NULL
  );