
WITH 
SUBSIDIARY AS
(
	SELECT DISTINCT HASH(UPPER(DATAAREAID)) FROM fersads.ds_InventTrans_FER UNION ALL SELECT DISTINCT HASH(UPPER(DATAAREAID)) FROM fersads.ds_InventTrans_CHN_HIST
),

PARAMS AS (
    SELECT
    		DATE '2026-04-30' AS CLOSINGDATE,
    		'INVENTSUM' AS STOCK_SOURCE, -- valores posibles: 'FINANCIAL_CLOSING' o 'INVENTSUM'
    		'FINANCIAL' AS DATE_MODE -- valores: 'PHYSICAL' o 'FINANCIAL'
),

ExchangeRatesLatest AS (
    SELECT
        erda.FROMCURRENCYCODE,
        erda.TOCURRENCYCODE,
        erda.EXCHANGERATE,
        ROW_NUMBER() OVER (
            PARTITION BY erda.FROMCURRENCYCODE, erda.TOCURRENCYCODE
            ORDER BY erda.VALIDFROM DESC
        ) AS RN
    FROM fersadv.ExchangeRateDaily_ALL erda
    CROSS JOIN PARAMS P
    WHERE erda.VALIDFROM <= P.CLOSINGDATE
),
ExchangeRatesPairs AS (
    -- Directos
    SELECT
        FROMCURRENCYCODE,
        TOCURRENCYCODE,
        EXCHANGERATE
    FROM ExchangeRatesLatest
    WHERE RN = 1

    UNION ALL

    -- Inversos
    SELECT
        TOCURRENCYCODE AS FROMCURRENCYCODE,
        FROMCURRENCYCODE AS TOCURRENCYCODE,
        1 / NULLIF(EXCHANGERATE, 0) AS EXCHANGERATE
    FROM ExchangeRatesLatest
    WHERE RN = 1
),
ExchangeRates AS (
    SELECT
        C.CURRENCY,
        COALESCE(
            MAX(CASE WHEN D_EUR.TOCURRENCYCODE = 'EUR' THEN D_EUR.EXCHANGERATE END),
            MAX(D_USD.EXCHANGERATE * USD_EUR.EXCHANGERATE)
        ) AS EXCHANGERATE_EUR,
        COALESCE(
            MAX(CASE WHEN D_USD.TOCURRENCYCODE = 'USD' THEN D_USD.EXCHANGERATE END),
            MAX(D_EUR.EXCHANGERATE * EUR_USD.EXCHANGERATE)
        ) AS EXCHANGERATE_USD
    FROM (
        SELECT DISTINCT CURRENCY
        FROM fersaSS.ds_StockFinancialMonthClosing
    ) C
    LEFT JOIN ExchangeRatesPairs D_EUR
        ON D_EUR.FROMCURRENCYCODE = C.CURRENCY
        AND D_EUR.TOCURRENCYCODE = 'EUR'
    LEFT JOIN ExchangeRatesPairs D_USD
        ON D_USD.FROMCURRENCYCODE = C.CURRENCY
        AND D_USD.TOCURRENCYCODE = 'USD'
    LEFT JOIN ExchangeRatesPairs EUR_USD
        ON EUR_USD.FROMCURRENCYCODE = 'EUR'
        AND EUR_USD.TOCURRENCYCODE = 'USD'
    LEFT JOIN ExchangeRatesPairs USD_EUR
        ON USD_EUR.FROMCURRENCYCODE = 'USD'
        AND USD_EUR.TOCURRENCYCODE = 'EUR'
    GROUP BY
        C.CURRENCY
),

StockBase AS 
(
    SELECT
        S.SUBSIDIARYID,
        S.INVENTLOCATIONID,
        S.ITEMID,
        '' AS INVENTSTATUSID,
        S.QUANTITY AS PHYSICALINVENT,
        S.AMOUNT / NULLIF(S.QUANTITY, 0) AS UNITCOST_LOCAL,
        CASE
            WHEN S.CURRENCY = 'EUR' THEN S.AMOUNT / NULLIF(S.QUANTITY, 0)
            ELSE (S.AMOUNT / NULLIF(S.QUANTITY, 0)) * ER.EXCHANGERATE_EUR
        END AS UNITCOST_EUR,
        CASE
            WHEN S.CURRENCY = 'USD' THEN S.AMOUNT / NULLIF(S.QUANTITY, 0)
            ELSE (S.AMOUNT / NULLIF(S.QUANTITY, 0)) * ER.EXCHANGERATE_USD
        END AS UNITCOST_USD
    FROM fersaSS.ds_StockFinancialMonthClosing S
    CROSS JOIN PARAMS P
    LEFT JOIN ExchangeRates ER
        ON ER.CURRENCY = S.CURRENCY
    WHERE P.STOCK_SOURCE = 'FINANCIAL_CLOSING'
      AND S.QUANTITY > 0
      AND S.CLOSINGDATE = P.CLOSINGDATE

    UNION ALL

    SELECT
        S.SUBSIDIARYID,
        S.INVENTLOCATIONID,
        S.ITEMID,
        S.INVENTSTATUSID,
        S.PHYSICALINVENT,
        S.UNITCOST AS UNITCOST_LOCAL,
        S.UNITCOST * S.EXCHANGERATE_EUR AS UNITCOST_EUR,
        S.UNITCOST * S.EXCHANGERATE_USD AS UNITCOST_USD
    FROM fersaSSTest.InventSum_FACT_HIST S
    CROSS JOIN PARAMS P
    WHERE P.STOCK_SOURCE = 'INVENTSUM'
    	  AND UPDATEDATE=P.CLOSINGDATE
    	  AND S.PHYSICALINVENT > 0
),
-- stock normalizado por subsidiary + location + item + status
Stock_norm_status AS 
(
    SELECT
        COALESCE(wlea.SUBSIDIARYID_TO, S.SUBSIDIARYID) AS SUBSIDIARYID,
        COALESCE(wlea.INVENTLOCATIONID_TO, S.INVENTLOCATIONID) AS INVENTLOCATIONID,
        S.ITEMID,
        S.INVENTSTATUSID,
        SUM(S.PHYSICALINVENT) AS PHYSICALINVENT,
		SUM(S.UNITCOST_EUR * S.PHYSICALINVENT)
		    / NULLIF(SUM(CASE WHEN S.UNITCOST_EUR IS NOT NULL THEN S.PHYSICALINVENT ELSE 0 END), 0)
		    AS UNITCOST_EUR,
		SUM(S.UNITCOST_USD * S.PHYSICALINVENT)
		    / NULLIF(SUM(CASE WHEN S.UNITCOST_USD IS NOT NULL THEN S.PHYSICALINVENT ELSE 0 END), 0)
		    AS UNITCOST_USD,
		SUM(S.UNITCOST_LOCAL * S.PHYSICALINVENT)
		    / NULLIF(SUM(S.PHYSICALINVENT), 0)
		    AS UNITCOST_LOCAL
    FROM StockBase S
    CROSS JOIN PARAMS P
    LEFT JOIN fersaSS.WarehouseLocationEquivalences_ALL wlea 
        ON wlea.MODEL = STOCK_SOURCE
        AND wlea.SUBSIDIARYID_FROM = S.SUBSIDIARYID
        AND wlea.INVENTLOCATIONID_FROM <=> S.INVENTLOCATIONID
    GROUP BY
        COALESCE(wlea.SUBSIDIARYID_TO, S.SUBSIDIARYID),
        COALESCE(wlea.INVENTLOCATIONID_TO, S.INVENTLOCATIONID),
        S.ITEMID,S.INVENTSTATUSID
    HAVING SUM(S.PHYSICALINVENT) > 0
),
-- stock normalizado por subsidiary + location + item
Stock_norm AS 
(
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        SUM(PHYSICALINVENT) AS PHYSICALINVENT
    FROM Stock_norm_status
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
    HAVING SUM(PHYSICALINVENT) > 0
),


NOFER_SalesBase AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        0 AS REFERENCECATEGORY,
        SALESID AS REFERENCEID,
        1 AS STATUSISSUE,
        0 AS STATUSRECEIPT,
        INVOICEDATE AS DATEPHYSICAL,
        INVOICEDATE AS DATEFINANCIAL,
        -INVOICEQTY AS QTY
    FROM fersadv.SalesInvoices_ALL
    WHERE HASH(SUBSIDIARYID) NOT IN (SELECT * FROM SUBSIDIARY)
    		OR (SUBSIDIARYID='PMEX' AND INVOICEDATE<'2026-04-30')
),
NOFER_PurchaseBase_sinPFI AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        3 AS REFERENCECATEGORY,
        PURCHASEID AS REFERENCEID,
        0 AS STATUSISSUE,
        1 AS STATUSRECEIPT,
        INVOICEDATE+60 AS DATEPHYSICAL,
        INVOICEDATE+60 AS DATEFINANCIAL,
        INVOICEQTY AS QTY
    FROM fersadv.PurchaseInvoices_ALL
    CROSS JOIN PARAMS P
    WHERE HASH(SUBSIDIARYID) NOT IN (SELECT * FROM SUBSIDIARY)
    		OR (SUBSIDIARYID='PMEX' AND INVOICEDATE<'2026-04-30')
    		AND INVOICEDATE+60<=P.CLOSINGDATE
),
NOFER_PurchaseBase_PFI as (
SELECT 
        cvics.TODATAAREAID AS SUBSIDIARYID,
        NULL AS INVENTLOCATIONID,
        sia.ITEMID,
        3 AS REFERENCECATEGORY,
        sia.SALESID AS REFERENCEID,
        0 AS STATUSISSUE,
        1 AS STATUSRECEIPT,
        sia.INVOICEDATE+60 AS DATEPHYSICAL,
        sia.INVOICEDATE+60 AS DATEFINANCIAL,
        sia.INVOICEQTY AS QTY
FROM FERSADV.SalesInvoices_ALL sia
LEFT JOIN FERSAPARAMSPUBLIC.CustomerVendorInterCo_standalone cvics 
	ON sia.CUSTOMERID = CVICS.CUSTVENDACCOUNT
	AND SIA.SUBSIDIARYID=CVICS.FROMDATAAREAID
	and CVICS."DEFAULT"  IS TRUE
CROSS JOIN PARAMS P
WHERE
    HASH(CVICS.TODATAAREAID) NOT IN (SELECT * FROM SUBSIDIARY)
    AND
	    	(CVICS.TODATAAREAID='PARG'
		OR CVICS.TODATAAREAID='PBOL'
		OR CVICS.TODATAAREAID='PCHI'
		OR CVICS.TODATAAREAID='PCOL'
		OR CVICS.TODATAAREAID='PKEN'
		OR (CVICS.TODATAAREAID='PMEX'
		AND SIA.INVOICEDATE <'2026-04-30'))
	AND SIA.INVOICEDATE+60 <= P.CLOSINGDATE
GROUP BY
    cvics.TODATAAREAID,sia.ITEMID,sia.SALESID,
    sia.INVOICEDATE,sia.INVOICEQTY
),
FER_TransactionsBase AS
(
    SELECT
        UPPER(IT.DATAAREAID) AS SUBSIDIARYID, ID.INVENTLOCATIONID,IT.ITEMID,
        IO.REFERENCECATEGORY,IO.REFERENCEID,IT.STATUSISSUE,IT.STATUSRECEIPT,
        IT.DATEPHYSICAL,IT.DATEFINANCIAL,
        SUM(IT.QTY) AS QTY
    FROM fersads.ds_InventTransOrigin_FER IO
    INNER JOIN fersads.ds_InventTrans_FER IT
        ON IO.RECID = IT.INVENTTRANSORIGIN
        AND IO.DATAAREAID = IT.DATAAREAID
    INNER JOIN fersads.ds_InventDim_FER ID
        ON IT.INVENTDIMID = ID.INVENTDIMID
        AND IT.DATAAREAID = ID.DATAAREAID
    WHERE
		HASH(UPPER(IT.DATAAREAID)) IN (SELECT * FROM SUBSIDIARY)
		AND (IT.STATUSISSUE = 1 OR IT.STATUSISSUE = 0 OR IT.STATUSISSUE IS NULL)
        AND (IT.STATUSRECEIPT < 2 OR IT.STATUSRECEIPT IS NULL)
    GROUP BY
        UPPER(IT.DATAAREAID), ID.INVENTLOCATIONID,IT.ITEMID,
        IO.REFERENCECATEGORY,IO.REFERENCEID,IT.STATUSISSUE,IT.STATUSRECEIPT,
        IT.DATEPHYSICAL,IT.DATEFINANCIAL

    UNION ALL

    SELECT
        UPPER(IT.DATAAREAID) AS SUBSIDIARYID, ID.INVENTLOCATIONID,IT.ITEMID,
        IO.REFERENCECATEGORY,IO.REFERENCEID,IT.STATUSISSUE,IT.STATUSRECEIPT,
        IT.DATEPHYSICAL,IT.DATEFINANCIAL,
        SUM(IT.QTY) AS QTY
    FROM fersads.ds_InventTransOrigin_CHN_HIST IO
    INNER JOIN fersads.ds_InventTrans_CHN_HIST IT
        ON IO.RECID = IT.INVENTTRANSORIGIN
        AND IO.DATAAREAID = IT.DATAAREAID
    INNER JOIN fersads.ds_InventDim_CHN_HIST ID
        ON IT.INVENTDIMID = ID.INVENTDIMID
        AND IT.DATAAREAID = ID.DATAAREAID
    WHERE
		HASH(UPPER(IT.DATAAREAID)) IN (SELECT * FROM SUBSIDIARY)
		AND (IT.STATUSISSUE = 1 OR IT.STATUSISSUE = 0 OR IT.STATUSISSUE IS NULL)
        AND (IT.STATUSRECEIPT < 2 OR IT.STATUSRECEIPT IS NULL)
    GROUP BY
        UPPER(IT.DATAAREAID), ID.INVENTLOCATIONID,IT.ITEMID,
        IO.REFERENCECATEGORY,IO.REFERENCEID,IT.STATUSISSUE,IT.STATUSRECEIPT,
        IT.DATEPHYSICAL,IT.DATEFINANCIAL
),
ALL_TransactionsBase AS (
    SELECT * FROM NOFER_SalesBase
    UNION ALL
    SELECT * FROM NOFER_PurchaseBase_sinPFI
    UNION ALL
    SELECT * FROM NOFER_PurchaseBase_PFI
    UNION ALL
    SELECT * FROM FER_TransactionsBase
),
-- Normalizamos las transacciones con las equivalencias
TransactionsBase_norm AS (
    SELECT
        COALESCE(wlea.SUBSIDIARYID_TO, T.SUBSIDIARYID) AS SUBSIDIARYID,
        COALESCE(wlea.INVENTLOCATIONID_TO, T.INVENTLOCATIONID) AS INVENTLOCATIONID,
        T.ITEMID,
        T.REFERENCECATEGORY,
        T.REFERENCEID,
        T.STATUSISSUE,
        T.STATUSRECEIPT,
        CASE
            WHEN P.DATE_MODE = 'FINANCIAL' THEN T.DATEFINANCIAL
            ELSE T.DATEPHYSICAL
        END AS TRANSDATE,
        T.DATEPHYSICAL,
        T.DATEFINANCIAL,
        T.QTY
    FROM ALL_TransactionsBase T
    CROSS JOIN PARAMS P
    LEFT JOIN fersaSS.WarehouseLocationEquivalences_ALL wlea 
        ON wlea.MODEL = STOCK_SOURCE
        AND wlea.SUBSIDIARYID_FROM = T.SUBSIDIARYID
        AND wlea.INVENTLOCATIONID_FROM <=> T.INVENTLOCATIONID
)
SELECT
    'TRANSACCIONES' AS ORIGEN,
    t.SUBSIDIARYID,
    t.INVENTLOCATIONID,
    COUNT(*) AS NUM_REGISTROS,
    SUM(t.QTY) AS QTY
FROM TransactionsBase_norm t
WHERE EXISTS (
    SELECT 1
    FROM Stock_norm s
    WHERE s.ITEMID = t.ITEMID
)
AND (
       NULLIF(t.SUBSIDIARYID, '') IS NULL
    OR NULLIF(t.INVENTLOCATIONID, '') IS NULL
)
GROUP BY
    t.SUBSIDIARYID,
    t.INVENTLOCATIONID

UNION ALL

SELECT
    'STOCK' AS ORIGEN,
    s.SUBSIDIARYID,
    s.INVENTLOCATIONID,
    COUNT(*) AS NUM_REGISTROS,
    SUM(s.PHYSICALINVENT) AS QTY
FROM Stock_norm s
WHERE EXISTS (
    SELECT 1
    FROM TransactionsBase_norm t
    WHERE t.ITEMID = s.ITEMID
)
AND (
       NULLIF(s.SUBSIDIARYID, '') IS NULL
    OR NULLIF(s.INVENTLOCATIONID, '') IS NULL
)
GROUP BY
    s.SUBSIDIARYID,
    s.INVENTLOCATIONID

ORDER BY
    ORIGEN,
    SUBSIDIARYID,
    INVENTLOCATIONID;
/*
select t.SUBSIDIARYID , s.SUBSIDIARYID,
	t.INVENTLOCATIONID, s.INVENTLOCATIONID,
	--date_trunc('month',t.transdate),
	sum(t.qty) AS QTYTRANS, 
	sum(s.PHYSICALINVENT) AS STOCK
from TransactionsBase_norm t
full outer join Stock_norm s
on t.SUBSIDIARYID =s.SUBSIDIARYID
and t.INVENTLOCATIONID=s.INVENTLOCATIONID
and t.itemid=s.itemid
where NOT (t.SUBSIDIARYID <=> s.SUBSIDIARYID
	    AND t.INVENTLOCATIONID <=> s.INVENTLOCATIONID	)
group by t.SUBSIDIARYID , s.SUBSIDIARYID,
	t.INVENTLOCATIONID, s.INVENTLOCATIONID
	--,date_trunc('month',t.transdate)
order by t.SUBSIDIARYID , s.SUBSIDIARYID,
	t.INVENTLOCATIONID, s.INVENTLOCATIONID
	--,date_trunc('month',t.transdate)*/