DROP TABLE IF EXISTS fersaSSTest.ObsoleteItems_Debug_Integrated_ALL;

CREATE TABLE fersaSSTest.ObsoleteItems_Debug_Integrated_ALL AS

WITH
SUBSIDIARY AS (
    SELECT DISTINCT HASH(UPPER(DATAAREAID)) FROM fersads.ds_InventTrans_FER
    UNION ALL
    SELECT DISTINCT HASH(UPPER(DATAAREAID)) FROM fersads.ds_InventTrans_CHN_HIST
),

PARAMS AS (
    SELECT
        DATE '2026-04-30' AS CLOSINGDATE,
        'INVENTSUM' AS STOCK_SOURCE,
        'FINANCIAL' AS DATE_MODE
),

ExchangeRatesLatest AS (
    SELECT
        erda.FROMCURRENCYCODE,
        erda.TOCURRENCYCODE,
        erda.EXCHANGERATE,
        ROW_NUMBER() OVER (
            PARTITION BY erda.FROMCURRENCYCODE, erda.TOCURRENCYCODE
            ORDER BY erda.VALIDFROM DESC
        ) AS RN
    FROM fersadv.ExchangeRateDaily_ALL erda
    CROSS JOIN PARAMS P
    WHERE erda.VALIDFROM <= P.CLOSINGDATE
),

ExchangeRatesPairs AS (
    SELECT
        FROMCURRENCYCODE,
        TOCURRENCYCODE,
        EXCHANGERATE
    FROM ExchangeRatesLatest
    WHERE RN = 1

    UNION ALL

    SELECT
        TOCURRENCYCODE AS FROMCURRENCYCODE,
        FROMCURRENCYCODE AS TOCURRENCYCODE,
        1 / NULLIF(EXCHANGERATE, 0) AS EXCHANGERATE
    FROM ExchangeRatesLatest
    WHERE RN = 1
),

ExchangeRates AS (
    SELECT
        C.CURRENCY,
        COALESCE(
            MAX(CASE WHEN D_EUR.TOCURRENCYCODE = 'EUR' THEN D_EUR.EXCHANGERATE END),
            MAX(D_USD.EXCHANGERATE * USD_EUR.EXCHANGERATE)
        ) AS EXCHANGERATE_EUR,
        COALESCE(
            MAX(CASE WHEN D_USD.TOCURRENCYCODE = 'USD' THEN D_USD.EXCHANGERATE END),
            MAX(D_EUR.EXCHANGERATE * EUR_USD.EXCHANGERATE)
        ) AS EXCHANGERATE_USD
    FROM (
        SELECT DISTINCT CURRENCY
        FROM fersaSS.ds_StockFinancialMonthClosing
    ) C
    LEFT JOIN ExchangeRatesPairs D_EUR
        ON D_EUR.FROMCURRENCYCODE = C.CURRENCY
       AND D_EUR.TOCURRENCYCODE = 'EUR'
    LEFT JOIN ExchangeRatesPairs D_USD
        ON D_USD.FROMCURRENCYCODE = C.CURRENCY
       AND D_USD.TOCURRENCYCODE = 'USD'
    LEFT JOIN ExchangeRatesPairs EUR_USD
        ON EUR_USD.FROMCURRENCYCODE = 'EUR'
       AND EUR_USD.TOCURRENCYCODE = 'USD'
    LEFT JOIN ExchangeRatesPairs USD_EUR
        ON USD_EUR.FROMCURRENCYCODE = 'USD'
       AND USD_EUR.TOCURRENCYCODE = 'EUR'
    GROUP BY
        C.CURRENCY
),

/* ============================================================
   STOCK BASE DEL CALCULO ORIGINAL
   ============================================================ */
StockBase AS (
    SELECT
        S.SUBSIDIARYID,
        S.INVENTLOCATIONID,
        S.ITEMID,
        '' AS INVENTSTATUSID,
        S.QUANTITY AS PHYSICALINVENT,
        S.AMOUNT / NULLIF(S.QUANTITY, 0) AS UNITCOST_LOCAL,
        CASE
            WHEN S.CURRENCY = 'EUR' THEN S.AMOUNT / NULLIF(S.QUANTITY, 0)
            ELSE (S.AMOUNT / NULLIF(S.QUANTITY, 0)) * ER.EXCHANGERATE_EUR
        END AS UNITCOST_EUR,
        CASE
            WHEN S.CURRENCY = 'USD' THEN S.AMOUNT / NULLIF(S.QUANTITY, 0)
            ELSE (S.AMOUNT / NULLIF(S.QUANTITY, 0)) * ER.EXCHANGERATE_USD
        END AS UNITCOST_USD
    FROM fersaSS.ds_StockFinancialMonthClosing S
    CROSS JOIN PARAMS P
    LEFT JOIN ExchangeRates ER
        ON ER.CURRENCY = S.CURRENCY
    WHERE P.STOCK_SOURCE = 'FINANCIAL_CLOSING'
      AND S.CLOSINGDATE = P.CLOSINGDATE
      AND S.QUANTITY > 0

    UNION ALL

    SELECT
        S.SUBSIDIARYID,
        S.INVENTLOCATIONID,
        S.ITEMID,
        S.INVENTSTATUSID,
        S.PHYSICALINVENT,
        S.UNITCOST AS UNITCOST_LOCAL,
        S.UNITCOST * S.EXCHANGERATE_EUR AS UNITCOST_EUR,
        S.UNITCOST * S.EXCHANGERATE_USD AS UNITCOST_USD
    FROM fersaSSTest.InventSum_FACT_HIST S
    CROSS JOIN PARAMS P
    WHERE P.STOCK_SOURCE = 'INVENTSUM'
      AND S.UPDATEDATE = P.CLOSINGDATE
      AND S.PHYSICALINVENT > 0
),

Stock_norm_status AS (
    SELECT
        COALESCE(wlea.SUBSIDIARYID_TO, S.SUBSIDIARYID) AS SUBSIDIARYID,
        COALESCE(wlea.INVENTLOCATIONID_TO, S.INVENTLOCATIONID) AS INVENTLOCATIONID,
        S.ITEMID,
        S.INVENTSTATUSID,
        SUM(S.PHYSICALINVENT) AS PHYSICALINVENT,
        SUM(S.UNITCOST_EUR * S.PHYSICALINVENT)
            / NULLIF(SUM(CASE WHEN S.UNITCOST_EUR IS NOT NULL THEN S.PHYSICALINVENT ELSE 0 END), 0) AS UNITCOST_EUR,
        SUM(S.UNITCOST_USD * S.PHYSICALINVENT)
            / NULLIF(SUM(CASE WHEN S.UNITCOST_USD IS NOT NULL THEN S.PHYSICALINVENT ELSE 0 END), 0) AS UNITCOST_USD,
        SUM(S.UNITCOST_LOCAL * S.PHYSICALINVENT)
            / NULLIF(SUM(S.PHYSICALINVENT), 0) AS UNITCOST_LOCAL
    FROM StockBase S
    CROSS JOIN PARAMS P
    LEFT JOIN fersaSS.WarehouseLocationEquivalences_ALL wlea
        ON wlea.MODEL = P.STOCK_SOURCE
       AND wlea.SUBSIDIARYID_FROM = S.SUBSIDIARYID
       AND wlea.INVENTLOCATIONID_FROM <=> S.INVENTLOCATIONID
    GROUP BY
        COALESCE(wlea.SUBSIDIARYID_TO, S.SUBSIDIARYID),
        COALESCE(wlea.INVENTLOCATIONID_TO, S.INVENTLOCATIONID),
        S.ITEMID,
        S.INVENTSTATUSID
    HAVING SUM(S.PHYSICALINVENT) > 0
),

Stock_norm AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        SUM(PHYSICALINVENT) AS PHYSICALINVENT
    FROM Stock_norm_status
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
    HAVING SUM(PHYSICALINVENT) > 0
),

/* ============================================================
   STOCK FINANCIERO NORMALIZADO
   ============================================================ */
FinancialStockBase AS (
    SELECT
        S.SUBSIDIARYID,
        S.INVENTLOCATIONID,
        S.ITEMID,
        S.QUANTITY AS FINANCIAL_STOCK_QTY
    FROM fersaSS.ds_StockFinancialMonthClosing S
    CROSS JOIN PARAMS P
    WHERE S.CLOSINGDATE = P.CLOSINGDATE
      AND S.QUANTITY > 0
),

FinancialStock_norm AS (
    SELECT
        COALESCE(wlea.SUBSIDIARYID_TO, S.SUBSIDIARYID) AS SUBSIDIARYID,
        COALESCE(wlea.INVENTLOCATIONID_TO, S.INVENTLOCATIONID) AS INVENTLOCATIONID,
        S.ITEMID,
        SUM(S.FINANCIAL_STOCK_QTY) AS FINANCIAL_STOCK_QTY
    FROM FinancialStockBase S
    LEFT JOIN fersaSS.WarehouseLocationEquivalences_ALL wlea
        ON wlea.MODEL = 'FINANCIAL_CLOSING'
       AND wlea.SUBSIDIARYID_FROM = S.SUBSIDIARYID
       AND wlea.INVENTLOCATIONID_FROM <=> S.INVENTLOCATIONID
    GROUP BY
        COALESCE(wlea.SUBSIDIARYID_TO, S.SUBSIDIARYID),
        COALESCE(wlea.INVENTLOCATIONID_TO, S.INVENTLOCATIONID),
        S.ITEMID
),

/* ============================================================
   FINANCE OBSOLETE REPORT
   IMPORTANTE:
   - NINGBO se corrige a FBEA / NINGBO.
   - Si Finance no tiene almacen, dejamos INVENTLOCATIONID NULL.
   ============================================================ */
FinanceObsolete AS (
    SELECT
        CASE
            WHEN mfo.SUBSIDIARYID = 'NINGBO' THEN 'FBEA'
            ELSE mfo.SUBSIDIARYID
        END AS SUBSIDIARYID,

        CASE
            WHEN mfo.SUBSIDIARYID = 'NINGBO' THEN 'NINGBO'
            ELSE NULL
        END AS INVENTLOCATIONID,

        mfo.ITEMID,
        SUM(mfo.STOCKQTY) AS FINREP_OBSOLETE_QTY,
        SUM(mfo.CALCULATEDSDAMOUNT_EUR) AS FINREP_AMOUNT_STOCK_EUR,
        SUM(mfo.FINANCIALSDAMOUNT_EUR) AS FINREP_AMOUNT_FINANCE_EUR,
        COUNT(*) AS FINREP_LINES
    FROM fersads.ds_monthlyfinancialobsoletes_edc mfo
    CROSS JOIN PARAMS P
    WHERE mfo.UPLOADMONTH = P.CLOSINGDATE
    GROUP BY
        CASE
            WHEN mfo.SUBSIDIARYID = 'NINGBO' THEN 'FBEA'
            ELSE mfo.SUBSIDIARYID
        END,
        CASE
            WHEN mfo.SUBSIDIARYID = 'NINGBO' THEN 'NINGBO'
            ELSE NULL
        END,
        mfo.ITEMID
),

/* ============================================================
   TRANSACCIONES ORIGINALES
   ============================================================ */
NOFER_SalesBase AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        0 AS REFERENCECATEGORY,
        SALESID AS REFERENCEID,
        1 AS STATUSISSUE,
        0 AS STATUSRECEIPT,
        INVOICEDATE AS DATEPHYSICAL,
        INVOICEDATE AS DATEFINANCIAL,
        -INVOICEQTY AS QTY
    FROM fersadv.SalesInvoices_ALL
    WHERE HASH(SUBSIDIARYID) NOT IN (SELECT * FROM SUBSIDIARY)
       OR (SUBSIDIARYID = 'PMEX' AND INVOICEDATE < DATE '2026-04-30')
),

NOFER_PurchaseBase_sinPFI AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        3 AS REFERENCECATEGORY,
        PURCHASEID AS REFERENCEID,
        0 AS STATUSISSUE,
        1 AS STATUSRECEIPT,
        INVOICEDATE + 60 AS DATEPHYSICAL,
        INVOICEDATE + 60 AS DATEFINANCIAL,
        INVOICEQTY AS QTY
    FROM fersadv.PurchaseInvoices_ALL
    CROSS JOIN PARAMS P
    WHERE (
              HASH(SUBSIDIARYID) NOT IN (SELECT * FROM SUBSIDIARY)
           OR (SUBSIDIARYID = 'PMEX' AND INVOICEDATE < DATE '2026-04-30')
          )
      AND INVOICEDATE + 60 <= P.CLOSINGDATE
),

NOFER_PurchaseBase_PFI AS (
    SELECT
        cvics.TODATAAREAID AS SUBSIDIARYID,
        NULL AS INVENTLOCATIONID,
        sia.ITEMID,
        3 AS REFERENCECATEGORY,
        sia.SALESID AS REFERENCEID,
        0 AS STATUSISSUE,
        1 AS STATUSRECEIPT,
        sia.INVOICEDATE + 60 AS DATEPHYSICAL,
        sia.INVOICEDATE + 60 AS DATEFINANCIAL,
        sia.INVOICEQTY AS QTY
    FROM FERSADV.SalesInvoices_ALL sia
    LEFT JOIN FERSAPARAMSPUBLIC.CustomerVendorInterCo_standalone cvics
        ON sia.CUSTOMERID = cvics.CUSTVENDACCOUNT
       AND sia.SUBSIDIARYID = cvics.FROMDATAAREAID
       AND cvics."DEFAULT" IS TRUE
    CROSS JOIN PARAMS P
    WHERE (
              (
                  HASH(cvics.TODATAAREAID) NOT IN (SELECT * FROM SUBSIDIARY)
                  AND cvics.TODATAAREAID IN ('PARG','PBOL','PCHI','PCOL','PKEN')
              )
           OR (
                  cvics.TODATAAREAID = 'PMEX'
                  AND sia.INVOICEDATE < DATE '2026-04-30'
              )
          )
      AND sia.INVOICEDATE + 60 <= P.CLOSINGDATE
    GROUP BY
        cvics.TODATAAREAID,
        sia.ITEMID,
        sia.SALESID,
        sia.INVOICEDATE,
        sia.INVOICEQTY
),

FER_TransactionsBase AS (
    SELECT
        UPPER(IT.DATAAREAID) AS SUBSIDIARYID,
        ID.INVENTLOCATIONID,
        IT.ITEMID,
        IO.REFERENCECATEGORY,
        IO.REFERENCEID,
        IT.STATUSISSUE,
        IT.STATUSRECEIPT,
        IT.DATEPHYSICAL,
        IT.DATEFINANCIAL,
        SUM(IT.QTY) AS QTY
    FROM fersads.ds_InventTransOrigin_FER IO
    INNER JOIN fersads.ds_InventTrans_FER IT
        ON IO.RECID = IT.INVENTTRANSORIGIN
       AND IO.DATAAREAID = IT.DATAAREAID
    INNER JOIN fersads.ds_InventDim_FER ID
        ON IT.INVENTDIMID = ID.INVENTDIMID
       AND IT.DATAAREAID = ID.DATAAREAID
    WHERE HASH(UPPER(IT.DATAAREAID)) IN (SELECT * FROM SUBSIDIARY)
      AND (IT.STATUSISSUE = 1 OR IT.STATUSISSUE = 0 OR IT.STATUSISSUE IS NULL)
      AND (IT.STATUSRECEIPT < 2 OR IT.STATUSRECEIPT IS NULL)
    GROUP BY
        UPPER(IT.DATAAREAID),
        ID.INVENTLOCATIONID,
        IT.ITEMID,
        IO.REFERENCECATEGORY,
        IO.REFERENCEID,
        IT.STATUSISSUE,
        IT.STATUSRECEIPT,
        IT.DATEPHYSICAL,
        IT.DATEFINANCIAL

    UNION ALL

    SELECT
        UPPER(IT.DATAAREAID) AS SUBSIDIARYID,
        ID.INVENTLOCATIONID,
        IT.ITEMID,
        IO.REFERENCECATEGORY,
        IO.REFERENCEID,
        IT.STATUSISSUE,
        IT.STATUSRECEIPT,
        IT.DATEPHYSICAL,
        IT.DATEFINANCIAL,
        SUM(IT.QTY) AS QTY
    FROM fersads.ds_InventTransOrigin_CHN_HIST IO
    INNER JOIN fersads.ds_InventTrans_CHN_HIST IT
        ON IO.RECID = IT.INVENTTRANSORIGIN
       AND IO.DATAAREAID = IT.DATAAREAID
    INNER JOIN fersads.ds_InventDim_CHN_HIST ID
        ON IT.INVENTDIMID = ID.INVENTDIMID
       AND IT.DATAAREAID = ID.DATAAREAID
    WHERE HASH(UPPER(IT.DATAAREAID)) IN (SELECT * FROM SUBSIDIARY)
      AND (IT.STATUSISSUE = 1 OR IT.STATUSISSUE = 0 OR IT.STATUSISSUE IS NULL)
      AND (IT.STATUSRECEIPT < 2 OR IT.STATUSRECEIPT IS NULL)
    GROUP BY
        UPPER(IT.DATAAREAID),
        ID.INVENTLOCATIONID,
        IT.ITEMID,
        IO.REFERENCECATEGORY,
        IO.REFERENCEID,
        IT.STATUSISSUE,
        IT.STATUSRECEIPT,
        IT.DATEPHYSICAL,
        IT.DATEFINANCIAL
),

ALL_TransactionsBase AS (
    SELECT * FROM NOFER_SalesBase
    UNION ALL
    SELECT * FROM NOFER_PurchaseBase_sinPFI
    UNION ALL
    SELECT * FROM NOFER_PurchaseBase_PFI
    UNION ALL
    SELECT * FROM FER_TransactionsBase
),

TransactionsBase_norm AS (
    SELECT
        COALESCE(wlea.SUBSIDIARYID_TO, T.SUBSIDIARYID) AS SUBSIDIARYID,
        COALESCE(wlea.INVENTLOCATIONID_TO, T.INVENTLOCATIONID) AS INVENTLOCATIONID,
        T.ITEMID,
        T.REFERENCECATEGORY,
        T.REFERENCEID,
        T.STATUSISSUE,
        T.STATUSRECEIPT,
        CASE
            WHEN P.DATE_MODE = 'FINANCIAL' THEN T.DATEFINANCIAL
            ELSE T.DATEPHYSICAL
        END AS TRANSDATE,
        T.DATEPHYSICAL,
        T.DATEFINANCIAL,
        T.QTY
    FROM ALL_TransactionsBase T
    CROSS JOIN PARAMS P
    LEFT JOIN fersaSS.WarehouseLocationEquivalences_ALL wlea
        ON wlea.MODEL = P.STOCK_SOURCE
       AND wlea.SUBSIDIARYID_FROM = T.SUBSIDIARYID
       AND wlea.INVENTLOCATIONID_FROM <=> T.INVENTLOCATIONID
),

Transactions2Y AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        REFERENCECATEGORY,
        REFERENCEID,
        STATUSISSUE,
        STATUSRECEIPT,
        TRANSDATE,
        DATEPHYSICAL,
        DATEFINANCIAL,
        SUM(QTY) AS QTY
    FROM TransactionsBase_norm
    CROSS JOIN PARAMS P
    WHERE REFERENCECATEGORY IN (8, 2, 0, 3, 22, 21)
      AND TRANSDATE >= P.CLOSINGDATE - (365 * 2)
      AND TRANSDATE <= P.CLOSINGDATE
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        REFERENCECATEGORY,
        REFERENCEID,
        STATUSISSUE,
        STATUSRECEIPT,
        TRANSDATE,
        DATEPHYSICAL,
        DATEFINANCIAL
),

OPWithNORW AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        SUM(QTY) AS QTY
    FROM (
        SELECT
            SUBSIDIARYID,
            INVENTLOCATIONID,
            ITEMID,
            REFERENCEID,
            SUM(QTY) AS QTY
        FROM Transactions2Y
        CROSS JOIN PARAMS P
        WHERE (STATUSISSUE = 1 OR STATUSRECEIPT = 1)
          AND (REFERENCECATEGORY = 8 OR REFERENCECATEGORY = 2)
          AND TRANSDATE >= P.CLOSINGDATE - (365 * 2)
        GROUP BY
            SUBSIDIARYID,
            INVENTLOCATIONID,
            ITEMID,
            REFERENCEID
        HAVING SUM(QTY) < 0
    ) A
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
    HAVING SUM(QTY) < 0
),

LAST2YEARS AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        SUM(CONSUMQTY) AS CONSUMQTY
    FROM (
        SELECT
            SUBSIDIARYID,
            INVENTLOCATIONID,
            ITEMID,
            -QTY AS CONSUMQTY
        FROM OPWithNORW

        UNION ALL

        SELECT
            SUBSIDIARYID,
            INVENTLOCATIONID,
            ITEMID,
            -SUM(QTY) AS CONSUMQTY
        FROM Transactions2Y
        CROSS JOIN PARAMS P
        WHERE (REFERENCECATEGORY = 0 OR REFERENCECATEGORY = 21)
          AND TRANSDATE >= P.CLOSINGDATE - (365 * 2)
        GROUP BY
            SUBSIDIARYID,
            INVENTLOCATIONID,
            ITEMID
        HAVING SUM(QTY) < 0
    ) A
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
),

LAST6M AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        SUM(PRODQTY) AS PRODQTY
    FROM (
        SELECT
            SUBSIDIARYID,
            INVENTLOCATIONID,
            ITEMID,
            SUM(QTY) AS PRODQTY
        FROM Transactions2Y
        CROSS JOIN PARAMS P
        WHERE (REFERENCECATEGORY = 2 OR REFERENCECATEGORY = 3 OR REFERENCECATEGORY = 22)
          AND TRANSDATE >= P.CLOSINGDATE - 183
          AND TRANSDATE <= P.CLOSINGDATE
        GROUP BY
            SUBSIDIARYID,
            INVENTLOCATIONID,
            ITEMID
        HAVING SUM(QTY) > 0
    ) B
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
),

FIRSTDATE AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        MIN(TRANSDATE) AS FIRSTINVOICEDATE
    FROM TransactionsBase_norm
    CROSS JOIN PARAMS P
    WHERE REFERENCECATEGORY IN (2, 3, 22)
      AND TRANSDATE <= P.CLOSINGDATE
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
    HAVING SUM(QTY) > 0
),

NORMAL AS (
    SELECT
        S.SUBSIDIARYID,
        S.INVENTLOCATIONID,
        S.ITEMID,
        S.PHYSICALINVENT,
        LY.CONSUMQTY
    FROM Stock_norm S
    LEFT JOIN LAST2YEARS LY
        ON S.SUBSIDIARYID = LY.SUBSIDIARYID
       AND S.ITEMID = LY.ITEMID
       AND S.INVENTLOCATIONID = LY.INVENTLOCATIONID
    LEFT JOIN LAST6M LM
        ON S.SUBSIDIARYID = LM.SUBSIDIARYID
       AND S.ITEMID = LM.ITEMID
       AND S.INVENTLOCATIONID = LM.INVENTLOCATIONID
    LEFT JOIN FIRSTDATE FD
        ON S.SUBSIDIARYID = FD.SUBSIDIARYID
       AND S.ITEMID = FD.ITEMID
       AND S.INVENTLOCATIONID = FD.INVENTLOCATIONID
    CROSS JOIN PARAMS P
    WHERE LM.ITEMID IS NULL
      AND (
             FD.FIRSTINVOICEDATE <= P.CLOSINGDATE - 365
          OR FD.FIRSTINVOICEDATE IS NULL
      )
      AND (
             S.PHYSICALINVENT > ABS(LY.CONSUMQTY)
          OR (S.PHYSICALINVENT > 0 AND LY.CONSUMQTY IS NULL)
      )
),

LOWROT AS (
    SELECT
        S.SUBSIDIARYID,
        S.INVENTLOCATIONID,
        S.ITEMID,
        S.PHYSICALINVENT,
        LY.CONSUMQTY
    FROM Stock_norm S
    LEFT JOIN LAST2YEARS LY
        ON S.SUBSIDIARYID = LY.SUBSIDIARYID
       AND S.ITEMID = LY.ITEMID
       AND S.INVENTLOCATIONID = LY.INVENTLOCATIONID
    WHERE (
              S.PHYSICALINVENT > ABS(LY.CONSUMQTY)
           OR (S.PHYSICALINVENT > 0 AND LY.CONSUMQTY IS NULL)
          )
      AND S.SUBSIDIARYID = 'FBEA'
      AND HASH(S.SUBSIDIARYID, S.INVENTLOCATIONID, S.ITEMID) NOT IN (
            SELECT HASH(SUBSIDIARYID, INVENTLOCATIONID, ITEMID)
            FROM NORMAL
      )
),

OBSOLETE AS (
    SELECT
        S.SUBSIDIARYID,
        S.ITEMID,
        S.INVENTLOCATIONID,
        S.INVENTSTATUSID,
        S.PHYSICALINVENT AS OBSOLETEQTY,
        S.UNITCOST_EUR,
        S.UNITCOST_USD,
        S.UNITCOST_LOCAL,
        CASE
            WHEN S.SUBSIDIARYID <> 'FBEA' THEN 'DAILY'
            WHEN S.SUBSIDIARYID = 'FBEA'
             AND ia.CATALOG NOT LIKE 'EXT%'
             AND ia.ITEMGROUP LIKE 'TERM%'
                THEN 'DAILY-FBEA-FG'
            WHEN S.SUBSIDIARYID = 'FBEA'
             AND (
                    ia.CATALOG LIKE 'EXT%'
                 OR ia.ITEMGROUP NOT LIKE 'TERM%'
                 )
                THEN 'DAILY-FBEA-RM'
        END AS FLAG
    FROM Stock_norm_status S
    INNER JOIN NORMAL
        ON HASH(NORMAL.SUBSIDIARYID, NORMAL.INVENTLOCATIONID, NORMAL.ITEMID)
         = HASH(S.SUBSIDIARYID, S.INVENTLOCATIONID, S.ITEMID)
    LEFT JOIN fersadv.Item_ALL ia
        ON HASH(ia.SUBSIDIARYID, ia.ITEMID)
         = HASH(S.SUBSIDIARYID, S.ITEMID)

    UNION ALL

    SELECT
        S.SUBSIDIARYID,
        S.ITEMID,
        S.INVENTLOCATIONID,
        S.INVENTSTATUSID,
        S.PHYSICALINVENT AS OBSOLETEQTY,
        S.UNITCOST_EUR,
        S.UNITCOST_USD,
        S.UNITCOST_LOCAL,
        'DAILY-FBEA-LOWROT' AS FLAG
    FROM Stock_norm_status S
    INNER JOIN LOWROT
        ON HASH(LOWROT.SUBSIDIARYID, LOWROT.INVENTLOCATIONID, LOWROT.ITEMID)
         = HASH(S.SUBSIDIARYID, S.INVENTLOCATIONID, S.ITEMID)

    UNION ALL

    SELECT
        S.SUBSIDIARYID,
        S.ITEMID,
        S.INVENTLOCATIONID,
        S.INVENTSTATUSID,
        S.PHYSICALINVENT AS OBSOLETEQTY,
        S.UNITCOST_EUR,
        S.UNITCOST_USD,
        S.UNITCOST_LOCAL,
        'DAILY-FBEA-QUALITY' AS FLAG
    FROM Stock_norm_status S
    WHERE S.SUBSIDIARYID = 'FBEA'
      AND S.INVENTSTATUSID NOT IN ('Available', 'Firewall', 'NoPacked', '')
      AND HASH(SUBSIDIARYID, INVENTLOCATIONID, ITEMID) NOT IN (
            SELECT HASH(SUBSIDIARYID, INVENTLOCATIONID, ITEMID)
            FROM NORMAL
      )
      AND HASH(SUBSIDIARYID, INVENTLOCATIONID, ITEMID) NOT IN (
            SELECT HASH(SUBSIDIARYID, INVENTLOCATIONID, ITEMID)
            FROM LOWROT
      )
),

/* ============================================================
   AGREGADOS A NIVEL SUBSIDIARY + INVENTLOCATION + ITEM
   SIN INVENTSTATUS COMO DIMENSION PARA NO DUPLICAR
   ============================================================ */
CalcStock_loc AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        SUM(PHYSICALINVENT) AS CALC_STOCK_QTY_LOC
    FROM Stock_norm
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
),

FinancialStock_loc AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        SUM(FINANCIAL_STOCK_QTY) AS FINANCIAL_STOCK_QTY_LOC
    FROM FinancialStock_norm
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
),

StockDebug_loc AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        SUM(PHYSICALINVENT) AS STOCK_QTY_LOC,
        ROUND(SUM(PHYSICALINVENT * UNITCOST_EUR), 2) AS STOCK_AMOUNT_EUR_LOC,
        COUNT(*) AS STOCK_LINES_LOC,
        COUNT(DISTINCT INVENTSTATUSID) AS STOCK_STATUS_COUNT_LOC,
        SUM(
            CASE
                WHEN INVENTSTATUSID NOT IN ('Available', 'Firewall', 'NoPacked', '')
                THEN PHYSICALINVENT
                ELSE 0
            END
        ) AS STOCK_QTY_NON_AVAILABLE_STATUS_LOC
    FROM Stock_norm_status
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
),

ObsoleteCalc_loc AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        SUM(OBSOLETEQTY) AS CALC_OBSOLETE_QTY_ALL_FLAGS_LOC,
        ROUND(SUM(OBSOLETEQTY * UNITCOST_EUR), 2) AS CALC_OBSOLETE_AMOUNT_EUR_ALL_FLAGS_LOC,
        COUNT(*) AS CALC_OBSOLETE_LINES_ALL_FLAGS_LOC,
        COUNT(DISTINCT INVENTSTATUSID) AS CALC_OBSOLETE_STATUS_COUNT_LOC,
        SUM(CASE WHEN FLAG IN ('DAILY', 'DAILY-FBEA-FG') THEN OBSOLETEQTY ELSE 0 END) AS CALC_OBSOLETE_QTY_FINANCE_FLAGS_ONLY_LOC,
        ROUND(SUM(CASE WHEN FLAG IN ('DAILY', 'DAILY-FBEA-FG') THEN OBSOLETEQTY * UNITCOST_EUR ELSE 0 END), 2) AS CALC_OBSOLETE_AMOUNT_EUR_FINANCE_FLAGS_ONLY_LOC
    FROM OBSOLETE
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
),

ObsoleteFinanceScope_loc AS (
    SELECT
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID,
        SUM(OBSOLETEQTY) AS CALC_OBSOLETE_QTY_FINANCE_SCOPE_LOC,
        ROUND(SUM(OBSOLETEQTY * UNITCOST_EUR), 2) AS CALC_OBSOLETE_AMOUNT_EUR_FINANCE_SCOPE_LOC,
        COUNT(*) AS CALC_OBSOLETE_LINES_FINANCE_SCOPE_LOC
    FROM OBSOLETE
    WHERE FLAG IN ('DAILY', 'DAILY-FBEA-FG')
      AND (
             (INVENTLOCATIONID NOT LIKE 'T_%' AND SUBSIDIARYID <> 'FBRA')
          OR (SUBSIDIARYID = 'PAUS' AND INVENTLOCATIONID NOT LIKE 'T_P0%')
          OR SUBSIDIARYID = 'FBRA'
      )
    GROUP BY
        SUBSIDIARYID,
        INVENTLOCATIONID,
        ITEMID
),

Criteria_loc AS (
    SELECT
        S.SUBSIDIARYID,
        S.INVENTLOCATIONID,
        S.ITEMID,
        MAX(CASE WHEN N.ITEMID IS NOT NULL THEN 1 ELSE 0 END) AS MATCHES_NORMAL_CTE,
        MAX(CASE WHEN LR.ITEMID IS NOT NULL THEN 1 ELSE 0 END) AS MATCHES_LOWROT_CTE,
        MAX(CASE WHEN S.SUBSIDIARYID = 'FBEA' AND SNS.INVENTSTATUSID NOT IN ('Available', 'Firewall', 'NoPacked', '') THEN 1 ELSE 0 END) AS MATCHES_QUALITY_RULE,
        SUM(COALESCE(LY.CONSUMQTY, 0)) AS CONSUMQTY_24M,
        SUM(COALESCE(LM.PRODQTY, 0)) AS RECEIPTQTY_6M,
        MIN(FD.FIRSTINVOICEDATE) AS FIRSTINVOICEDATE,
        MAX(CASE WHEN LM.ITEMID IS NULL THEN 1 ELSE 0 END) AS CRITERIA_NO_RECEIPT_6M,
        MAX(CASE WHEN FD.FIRSTINVOICEDATE <= P.CLOSINGDATE - 365 OR FD.FIRSTINVOICEDATE IS NULL THEN 1 ELSE 0 END) AS CRITERIA_NOT_NEW_12M,
        MAX(
            CASE
                WHEN S.PHYSICALINVENT > ABS(COALESCE(LY.CONSUMQTY, 0))
                  OR (S.PHYSICALINVENT > 0 AND LY.CONSUMQTY IS NULL)
                THEN 1 ELSE 0
            END
        ) AS CRITERIA_STOCK_GT_CONSUMPTION
    FROM Stock_norm S
    CROSS JOIN PARAMS P
    LEFT JOIN Stock_norm_status SNS
        ON SNS.SUBSIDIARYID <=> S.SUBSIDIARYID
       AND SNS.INVENTLOCATIONID <=> S.INVENTLOCATIONID
       AND SNS.ITEMID <=> S.ITEMID
    LEFT JOIN LAST2YEARS LY
        ON LY.SUBSIDIARYID <=> S.SUBSIDIARYID
       AND LY.INVENTLOCATIONID <=> S.INVENTLOCATIONID
       AND LY.ITEMID <=> S.ITEMID
    LEFT JOIN LAST6M LM
        ON LM.SUBSIDIARYID <=> S.SUBSIDIARYID
       AND LM.INVENTLOCATIONID <=> S.INVENTLOCATIONID
       AND LM.ITEMID <=> S.ITEMID
    LEFT JOIN FIRSTDATE FD
        ON FD.SUBSIDIARYID <=> S.SUBSIDIARYID
       AND FD.INVENTLOCATIONID <=> S.INVENTLOCATIONID
       AND FD.ITEMID <=> S.ITEMID
    LEFT JOIN NORMAL N
        ON N.SUBSIDIARYID <=> S.SUBSIDIARYID
       AND N.INVENTLOCATIONID <=> S.INVENTLOCATIONID
       AND N.ITEMID <=> S.ITEMID
    LEFT JOIN LOWROT LR
        ON LR.SUBSIDIARYID <=> S.SUBSIDIARYID
       AND LR.INVENTLOCATIONID <=> S.INVENTLOCATIONID
       AND LR.ITEMID <=> S.ITEMID
    GROUP BY
        S.SUBSIDIARYID,
        S.INVENTLOCATIONID,
        S.ITEMID
),

/* ============================================================
   TOTALES ITEM PARA COMPARAR CON FINREP SIN DUPLICAR POR ALMACEN
   ============================================================ */
CalcStock_item AS (
    SELECT
        SUBSIDIARYID,
        ITEMID,
        SUM(CALC_STOCK_QTY_LOC) AS CALC_STOCK_QTY_ITEM
    FROM CalcStock_loc
    GROUP BY
        SUBSIDIARYID,
        ITEMID
),

FinancialStock_item AS (
    SELECT
        SUBSIDIARYID,
        ITEMID,
        SUM(FINANCIAL_STOCK_QTY_LOC) AS FINANCIAL_STOCK_QTY_ITEM
    FROM FinancialStock_loc
    GROUP BY
        SUBSIDIARYID,
        ITEMID
),

ObsoleteFinanceScope_item AS (
    SELECT
        SUBSIDIARYID,
        ITEMID,
        SUM(CALC_OBSOLETE_QTY_FINANCE_SCOPE_LOC) AS CALC_OBSOLETE_QTY_FINANCE_SCOPE_ITEM,
        ROUND(SUM(CALC_OBSOLETE_AMOUNT_EUR_FINANCE_SCOPE_LOC), 2) AS CALC_OBSOLETE_AMOUNT_EUR_FINANCE_SCOPE_ITEM
    FROM ObsoleteFinanceScope_loc
    GROUP BY
        SUBSIDIARYID,
        ITEMID
),

FinalKeys AS (
    SELECT SUBSIDIARYID, INVENTLOCATIONID, ITEMID FROM CalcStock_loc
    UNION
    SELECT SUBSIDIARYID, INVENTLOCATIONID, ITEMID FROM FinancialStock_loc
    UNION
    SELECT SUBSIDIARYID, INVENTLOCATIONID, ITEMID FROM ObsoleteFinanceScope_loc
    UNION
    SELECT SUBSIDIARYID, INVENTLOCATIONID, ITEMID FROM FinanceObsolete
)

SELECT
    FK.SUBSIDIARYID,
    FK.INVENTLOCATIONID,
    FK.ITEMID,

    CSL.CALC_STOCK_QTY_LOC,
    FSL.FINANCIAL_STOCK_QTY_LOC,

    CSI.CALC_STOCK_QTY_ITEM,
    FSI.FINANCIAL_STOCK_QTY_ITEM,

    FO.FINREP_OBSOLETE_QTY,

    COALESCE(CSL.CALC_STOCK_QTY_LOC, 0)
      - COALESCE(FSL.FINANCIAL_STOCK_QTY_LOC, 0) AS DIFF_CALC_STOCK_VS_FINANCIAL_STOCK_QTY_LOC,

    COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0)
      - COALESCE(FSI.FINANCIAL_STOCK_QTY_ITEM, 0) AS DIFF_CALC_STOCK_VS_FINANCIAL_STOCK_QTY_ITEM,

    COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0)
      - COALESCE(FO.FINREP_OBSOLETE_QTY, 0) AS DIFF_CALC_STOCK_VS_FINREP_OBSOLETE_QTY_ITEM,

    COALESCE(FSI.FINANCIAL_STOCK_QTY_ITEM, 0)
      - COALESCE(FO.FINREP_OBSOLETE_QTY, 0) AS DIFF_FINANCIAL_STOCK_VS_FINREP_OBSOLETE_QTY_ITEM,

    CASE
        WHEN CSL.SUBSIDIARYID IS NULL THEN 'SIN_STOCK_CALC_LOC'
        WHEN FSL.SUBSIDIARYID IS NULL THEN 'SIN_STOCK_FINANCIERO_LOC'
        WHEN ABS(COALESCE(CSL.CALC_STOCK_QTY_LOC, 0) - COALESCE(FSL.FINANCIAL_STOCK_QTY_LOC, 0)) > 0.01
            THEN 'DIF_STOCK_CALC_VS_STOCK_FINANCIERO_LOC'
        ELSE 'OK_STOCK_CALC_VS_STOCK_FINANCIERO_LOC'
    END AS DEBUG_STOCK_CALC_VS_FINANCIAL_LOC,

    CASE
        WHEN CSI.SUBSIDIARYID IS NULL THEN 'SIN_STOCK_CALC_ITEM'
        WHEN FSI.SUBSIDIARYID IS NULL THEN 'SIN_STOCK_FINANCIERO_ITEM'
        WHEN ABS(COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0) - COALESCE(FSI.FINANCIAL_STOCK_QTY_ITEM, 0)) > 0.01
            THEN 'DIF_STOCK_CALC_VS_STOCK_FINANCIERO_ITEM'
        ELSE 'OK_STOCK_CALC_VS_STOCK_FINANCIERO_ITEM'
    END AS DEBUG_STOCK_CALC_VS_FINANCIAL_ITEM,

    CASE
        WHEN FO.SUBSIDIARYID IS NULL THEN 'SIN_FINREP_OBSOLETE'
        WHEN ABS(COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0) - COALESCE(FO.FINREP_OBSOLETE_QTY, 0)) > 0.01
            THEN 'DIF_STOCK_CALC_ITEM_VS_FINREP_OBSOLETE'
        ELSE 'OK_STOCK_CALC_ITEM_VS_FINREP_OBSOLETE'
    END AS DEBUG_STOCK_CALC_VS_FINREP_OBSOLETE,

    CASE
        WHEN FO.SUBSIDIARYID IS NULL THEN 'SIN_FINREP_OBSOLETE'
        WHEN FSI.SUBSIDIARYID IS NULL THEN 'SIN_STOCK_FINANCIERO_ITEM'
        WHEN ABS(COALESCE(FSI.FINANCIAL_STOCK_QTY_ITEM, 0) - COALESCE(FO.FINREP_OBSOLETE_QTY, 0)) > 0.01
            THEN 'DIF_STOCK_FINANCIERO_ITEM_VS_FINREP_OBSOLETE'
        ELSE 'OK_STOCK_FINANCIERO_ITEM_VS_FINREP_OBSOLETE'
    END AS DEBUG_STOCK_FINANCIAL_VS_FINREP_OBSOLETE,

    CASE
        WHEN ABS(COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0) - COALESCE(FSI.FINANCIAL_STOCK_QTY_ITEM, 0)) <= 0.01
         AND ABS(COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0) - COALESCE(FO.FINREP_OBSOLETE_QTY, 0)) <= 0.01
         AND ABS(COALESCE(FSI.FINANCIAL_STOCK_QTY_ITEM, 0) - COALESCE(FO.FINREP_OBSOLETE_QTY, 0)) <= 0.01
            THEN 'OK_3_STOCKS_COINCIDEN_ITEM'

        WHEN ABS(COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0) - COALESCE(FSI.FINANCIAL_STOCK_QTY_ITEM, 0)) <= 0.01
         AND ABS(COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0) - COALESCE(FO.FINREP_OBSOLETE_QTY, 0)) > 0.01
            THEN 'CALC_Y_STOCK_FINANCIERO_OK__FINREP_DIFIERE'

        WHEN ABS(COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0) - COALESCE(FO.FINREP_OBSOLETE_QTY, 0)) <= 0.01
         AND ABS(COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0) - COALESCE(FSI.FINANCIAL_STOCK_QTY_ITEM, 0)) > 0.01
            THEN 'CALC_Y_FINREP_OK__STOCK_FINANCIERO_DIFIERE'

        WHEN ABS(COALESCE(FSI.FINANCIAL_STOCK_QTY_ITEM, 0) - COALESCE(FO.FINREP_OBSOLETE_QTY, 0)) <= 0.01
         AND ABS(COALESCE(CSI.CALC_STOCK_QTY_ITEM, 0) - COALESCE(FSI.FINANCIAL_STOCK_QTY_ITEM, 0)) > 0.01
            THEN 'STOCK_FINANCIERO_Y_FINREP_OK__CALC_DIFIERE'

        WHEN CSI.SUBSIDIARYID IS NULL THEN 'FALTA_STOCK_CALC'
        WHEN FSI.SUBSIDIARYID IS NULL THEN 'FALTA_STOCK_FINANCIERO'
        WHEN FO.SUBSIDIARYID IS NULL THEN 'FALTA_FINREP_OBSOLETE'

        ELSE 'DIFIEREN_LOS_3_STOCKS'
    END AS STOCK_TRIANGULATION_DEBUG,

    SDL.STOCK_QTY_LOC,
    SDL.STOCK_AMOUNT_EUR_LOC,
    SDL.STOCK_LINES_LOC,
    SDL.STOCK_STATUS_COUNT_LOC,
    SDL.STOCK_QTY_NON_AVAILABLE_STATUS_LOC,

    CL.CONSUMQTY_24M,
    CL.RECEIPTQTY_6M,
    CL.FIRSTINVOICEDATE,
    CL.CRITERIA_NO_RECEIPT_6M,
    CL.CRITERIA_NOT_NEW_12M,
    CL.CRITERIA_STOCK_GT_CONSUMPTION,
    CL.MATCHES_NORMAL_CTE,
    CL.MATCHES_LOWROT_CTE,
    CL.MATCHES_QUALITY_RULE,

    OCL.CALC_OBSOLETE_QTY_ALL_FLAGS_LOC,
    OCL.CALC_OBSOLETE_AMOUNT_EUR_ALL_FLAGS_LOC,
    OCL.CALC_OBSOLETE_LINES_ALL_FLAGS_LOC,
    OCL.CALC_OBSOLETE_STATUS_COUNT_LOC,
    OCL.CALC_OBSOLETE_QTY_FINANCE_FLAGS_ONLY_LOC,
    OCL.CALC_OBSOLETE_AMOUNT_EUR_FINANCE_FLAGS_ONLY_LOC,

    OFSL.CALC_OBSOLETE_QTY_FINANCE_SCOPE_LOC,
    OFSL.CALC_OBSOLETE_AMOUNT_EUR_FINANCE_SCOPE_LOC,
    OFSL.CALC_OBSOLETE_LINES_FINANCE_SCOPE_LOC,

    OFSI.CALC_OBSOLETE_QTY_FINANCE_SCOPE_ITEM,
    OFSI.CALC_OBSOLETE_AMOUNT_EUR_FINANCE_SCOPE_ITEM,

    FO.FINREP_OBSOLETE_QTY AS FINREP_QTY,
    FO.FINREP_AMOUNT_STOCK_EUR,
    FO.FINREP_AMOUNT_FINANCE_EUR,
    FO.FINREP_LINES,

    COALESCE(OFSL.CALC_OBSOLETE_QTY_FINANCE_SCOPE_LOC, 0)
      - COALESCE(FO.FINREP_OBSOLETE_QTY, 0) AS DIFF_OBSOLETE_QTY_CALC_LOC_VS_FINREP,

    COALESCE(OFSI.CALC_OBSOLETE_QTY_FINANCE_SCOPE_ITEM, 0)
      - COALESCE(FO.FINREP_OBSOLETE_QTY, 0) AS DIFF_OBSOLETE_QTY_CALC_ITEM_VS_FINREP,

    ROUND(
        COALESCE(OFSI.CALC_OBSOLETE_AMOUNT_EUR_FINANCE_SCOPE_ITEM, 0)
        - COALESCE(FO.FINREP_AMOUNT_STOCK_EUR, 0),
        2
    ) AS DIFF_AMOUNT_CALC_ITEM_VS_FINREP_STOCK_EUR,

    ROUND(
        COALESCE(OFSI.CALC_OBSOLETE_AMOUNT_EUR_FINANCE_SCOPE_ITEM, 0)
        - COALESCE(FO.FINREP_AMOUNT_FINANCE_EUR, 0),
        2
    ) AS DIFF_AMOUNT_CALC_ITEM_VS_FINREP_FINANCE_EUR,

    CASE
        WHEN OFSI.SUBSIDIARYID IS NULL AND FO.SUBSIDIARYID IS NOT NULL THEN 'SOLO_FINREP'
        WHEN OFSI.SUBSIDIARYID IS NOT NULL AND FO.SUBSIDIARYID IS NULL THEN 'SOLO_CALC'
        WHEN ABS(COALESCE(OFSI.CALC_OBSOLETE_QTY_FINANCE_SCOPE_ITEM, 0) - COALESCE(FO.FINREP_OBSOLETE_QTY, 0)) > 0.01
            THEN 'DIF_QTY_OBSOLETO_ITEM'
        WHEN ABS(COALESCE(OFSI.CALC_OBSOLETE_AMOUNT_EUR_FINANCE_SCOPE_ITEM, 0) - COALESCE(FO.FINREP_AMOUNT_STOCK_EUR, 0)) > 0.01
            THEN 'DIF_AMOUNT_STOCK'
        WHEN ABS(COALESCE(OFSI.CALC_OBSOLETE_AMOUNT_EUR_FINANCE_SCOPE_ITEM, 0) - COALESCE(FO.FINREP_AMOUNT_FINANCE_EUR, 0)) > 0.01
            THEN 'DIF_AMOUNT_FINANCE'
        ELSE 'OK_CALC_VS_FINREP'
    END AS DEBUG_CALC_VS_FINREP,

    CASE
        WHEN FK.SUBSIDIARYID = 'FBEA'
         AND (
                FK.INVENTLOCATIONID = 'NINGBO'
             OR FK.INVENTLOCATIONID = 'Ningbo'
             OR FK.INVENTLOCATIONID = 'OnHand'
            )
            THEN 'REVISAR_NINGBO'
        ELSE NULL
    END AS NINGBO_DEBUG,

    P.CLOSINGDATE,
    P.STOCK_SOURCE,
    P.DATE_MODE

FROM FinalKeys FK
CROSS JOIN PARAMS P

LEFT JOIN CalcStock_loc CSL
    ON CSL.SUBSIDIARYID <=> FK.SUBSIDIARYID
   AND CSL.INVENTLOCATIONID <=> FK.INVENTLOCATIONID
   AND CSL.ITEMID <=> FK.ITEMID

LEFT JOIN FinancialStock_loc FSL
    ON FSL.SUBSIDIARYID <=> FK.SUBSIDIARYID
   AND FSL.INVENTLOCATIONID <=> FK.INVENTLOCATIONID
   AND FSL.ITEMID <=> FK.ITEMID

LEFT JOIN StockDebug_loc SDL
    ON SDL.SUBSIDIARYID <=> FK.SUBSIDIARYID
   AND SDL.INVENTLOCATIONID <=> FK.INVENTLOCATIONID
   AND SDL.ITEMID <=> FK.ITEMID

LEFT JOIN Criteria_loc CL
    ON CL.SUBSIDIARYID <=> FK.SUBSIDIARYID
   AND CL.INVENTLOCATIONID <=> FK.INVENTLOCATIONID
   AND CL.ITEMID <=> FK.ITEMID

LEFT JOIN ObsoleteCalc_loc OCL
    ON OCL.SUBSIDIARYID <=> FK.SUBSIDIARYID
   AND OCL.INVENTLOCATIONID <=> FK.INVENTLOCATIONID
   AND OCL.ITEMID <=> FK.ITEMID

LEFT JOIN ObsoleteFinanceScope_loc OFSL
    ON OFSL.SUBSIDIARYID <=> FK.SUBSIDIARYID
   AND OFSL.INVENTLOCATIONID <=> FK.INVENTLOCATIONID
   AND OFSL.ITEMID <=> FK.ITEMID

LEFT JOIN CalcStock_item CSI
    ON CSI.SUBSIDIARYID <=> FK.SUBSIDIARYID
   AND CSI.ITEMID <=> FK.ITEMID

LEFT JOIN FinancialStock_item FSI
    ON FSI.SUBSIDIARYID <=> FK.SUBSIDIARYID
   AND FSI.ITEMID <=> FK.ITEMID

LEFT JOIN ObsoleteFinanceScope_item OFSI
    ON OFSI.SUBSIDIARYID <=> FK.SUBSIDIARYID
   AND OFSI.ITEMID <=> FK.ITEMID

LEFT JOIN FinanceObsolete FO
    ON FO.SUBSIDIARYID <=> FK.SUBSIDIARYID
   AND FO.ITEMID <=> FK.ITEMID
   AND (
           FO.INVENTLOCATIONID <=> FK.INVENTLOCATIONID
        OR FO.INVENTLOCATIONID IS NULL
      )

ORDER BY
    FK.SUBSIDIARYID,
    FK.INVENTLOCATIONID,
    ABS(COALESCE(OFSI.CALC_OBSOLETE_QTY_FINANCE_SCOPE_ITEM, 0) - COALESCE(FO.FINREP_OBSOLETE_QTY, 0)) DESC;

 GRANT SELECT
ON fersaSSTest.ObsoleteItems_Debug_Integrated_ALL
TO usr_paula_carmona,
   usr_juan_lanero;
 
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER
ON fersaSSTest.ObsoleteItems_Debug_Integrated_ALL
TO usr_iago_trillo,
   usr_alejandro_villen;
